// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUwvtfZWSF7iubMCSVF-d0L0MvvtIqpM',
    appId: '1:726374824856:web:cf98d7fd0d97e1bd99c9ed',
    messagingSenderId: '726374824856',
    projectId: 'steadfast-list-406306',
    authDomain: 'steadfast-list-406306.firebaseapp.com',
    storageBucket: 'steadfast-list-406306.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9lmxnhNIeWZE7laPeSqcZ0txhUPql8I',
    appId: '1:726374824856:android:f05f81e4ac78414799c9ed',
    messagingSenderId: '726374824856',
    projectId: 'steadfast-list-406306',
    storageBucket: 'steadfast-list-406306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSM0AQE6arJ0xNXyyREJ1_BAUHdM3kMw',
    appId: '1:726374824856:ios:89cd285c9b5f2c3899c9ed',
    messagingSenderId: '726374824856',
    projectId: 'steadfast-list-406306',
    storageBucket: 'steadfast-list-406306.appspot.com',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSM0AQE6arJ0xNXyyREJ1_BAUHdM3kMw',
    appId: '1:726374824856:ios:9d4830635b500f4e99c9ed',
    messagingSenderId: '726374824856',
    projectId: 'steadfast-list-406306',
    storageBucket: 'steadfast-list-406306.appspot.com',
    iosBundleId: 'com.example.firebaseLearn.RunnerTests',
  );
}
